#!/usr/bin/env bash
#Install and setup nginx
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
service nginx start
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo nginx -t
sudo service nginx restart
