#!/usr/bin/env bash
#Configure your Nginx server so that /redirect_me is redirecting to another page
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
service nginx start
echo "Hello World!" | sudo tee /var/www/html/index.html
string_rep="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/ permanent;"
sudo sed -i "s/server_name _;/$string_rep/" /etc/nginx/sites-enabled/default
sudo nginx -t
sudo service nginx restart
