#!/usr/bin/env bash
#Configure your Nginx server to have a custom 404 page

sudo -c echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo sed -i '/server_name _;/ a\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html
sed -i '/server_name _;/ a\\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}\n' /etc/nginx/sites-available/default
service nginx restart
