#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 server
# Configure HAProxy to send traffic to web-01 and web-02 servers
# Distribute requests using a roundrobin algorithm
# Make sure that HAProxy can be managed via an init script

sudo apt-get -y update
sudo apt-get -y install haproxy

server_config=\
"
frontend  kagendo_frontend
        bind *:80
        mode http
        default_backend kagendo_backend
backend kagendo_backend
        balance roundrobin
        server 451215-web-01 52.3.251.217:80 check
        server 451215-web-02 35.153.57.127:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo haproxy -c -f /etc/haproxy/haproxy.cfg

sudo service haproxy restart

